# Importing libraries

In [71]:
import numpy as np
import pickle
import os
import sys
import random

## Defining constants

In [72]:
STATE_SIZE = (25,25)
ACTION_SIZE = 4

## Defining loading and saving of files

In [73]:
def load(filename):
    with open(filename, 'rb') as f:
        return pickle.load(f)

In [74]:
def save(filename, Q_table):
    with open(filename, 'wb') as f:
        pickle.dump(Q_table, f)

## Defining the static environment



In [75]:
class DroneGridEnv():

    def __init__(self, grid):

        self.grid = grid
        self.grid_size = np.array(grid).shape
        self.observation_space = (self.grid_size[0]), (self.grid_size[1])
        self.action_space = [0, 1, 2, 3] # 4 discrete actions: 0 = up, 1 = down, 2 = left, 3 = right
        self.start_pos = (0, 0)  # Starting position at top left corner
        self.goal_pos = (self.grid_size[0] - 1, self.grid_size[1] - 1)  # Goal position at bottom right corner
        self.current_pos = self.start_pos  # Initialize current position

    def reset(self):
        self.current_pos = self.start_pos  # Reset current position to start position
        return self.current_pos  # Return initial state

    def step(self, action):

        assert action in self.action_space, f"Invalid action {action}"  # Check if action is valid

        # Define movement based on action
        if action == 0:  # Up
            new_pos = (self.current_pos[0], self.current_pos[1] - 1)
        elif action == 1:  # Down
            new_pos = (self.current_pos[0], self.current_pos[1] + 1)
        elif action == 2:  # Left
            new_pos = (self.current_pos[0] - 1, self.current_pos[1])
        elif action == 3:  # Right
            new_pos = (self.current_pos[0] + 1, self.current_pos[1])

        # Check if new position is within bounds and not an obstacle
        if 0 <= new_pos[0] < self.grid_size[0] and 0 <= new_pos[1] < self.grid_size[1] and self.grid[new_pos[1]][new_pos[0]] != 1:

            self.current_pos = new_pos  # Update current position

            # Check if goal state is reached
            done = (self.current_pos == self.goal_pos)

            # Calculate reward
            if done:
                reward = 100.0  # Positive reward for reaching the goal

            elif self.grid[new_pos[1]][new_pos[0]] == 1:
                reward = -100 # Negative reward for going in a wall

            else:
                reward = 0 #Negative reward for non-goal state

        else:
            done = False
            reward = -100  # Negative reward for going out of bounds

        return self.current_pos, reward, done

Function to compute an action in function of the epsilon-greedy algorith

In [76]:
def compute_action(current_state, Q_table, epsilon, environment):

    if np.random.uniform(0,1) < epsilon:
        return np.random.choice(range(len(environment.action_space)))

    else:
        return np.argmax(Q_table[current_state])

Loading a personalized map

In [77]:
map = load('map_simple.pkl')
print(map)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0], [0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0], [0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Creating an instance of the environment through the loaded map

In [78]:
environment = DroneGridEnv(map)
print(environment.observation_space)
print(environment.action_space)


(25, 25)
[0, 1, 2, 3]


---
# Q-Learning
---


In [81]:
def q_learning(env, alpha=1, gamma=0.9,  epsilon=1, epsilon_decay=0.005):

    Q = np.zeros((env.grid_size[0]*env.grid_size[1], len(env.action_space)), dtype=np.float32) #Initialize the Q table to all 0s

    for e in range(1000): #Run 1k training runs

        state = env.reset() #Part of OpenAI where you need to reset at the start of each run
        total_reward = 0 #Set initial reward to 0

        while True: #Loop until done == True
            #IF random number is less than epsilon grab the random action else grab the argument max of Q[state]

            current_state_index = env.current_pos[0] + env.current_pos[1]*env.observation_space[0] # Obtain the index of the state

            action = compute_action(current_state_index, Q, epsilon, env) # Compute the action for the current state in function of the epsilon_greedy

            posp1, reward, done = env.step(action) #Send your action to OpenAI and get back the tuple

            state_tp1_index = posp1[0] + posp1[1]*env.observation_space[0]

            total_reward += reward #Increment your reward

            Q[current_state_index][action] = Q[current_state_index][action] + alpha * (reward + gamma * np.max(Q[state_tp1_index]) - Q[current_state_index][action])

             #Make sure to keep random at 10%

            if done:
                print(f"Episode: {e}, Reward: {total_reward}")
                break

        epsilon *= np.exp(-epsilon_decay)

    return Q

Effective running of the Q-Learning and saving of the trained Q-Table

In [82]:
q = q_learning(environment)
save('Q_Table - Q-Learning.pkl', q)

Episode: 0, Reward: -51500.0
Episode: 1, Reward: -23400.0
Episode: 2, Reward: -167100.0
Episode: 3, Reward: -15700.0
Episode: 4, Reward: -38600.0
Episode: 5, Reward: -13300.0
Episode: 6, Reward: -15200.0
Episode: 7, Reward: -118300.0
Episode: 8, Reward: -126400.0
Episode: 9, Reward: -7200.0
Episode: 10, Reward: -12600.0
Episode: 11, Reward: -6300.0
Episode: 12, Reward: -2800.0
Episode: 13, Reward: -11200.0
Episode: 14, Reward: -8400.0
Episode: 15, Reward: -6500.0
Episode: 16, Reward: -8800.0
Episode: 17, Reward: -2000.0
Episode: 18, Reward: -13200.0
Episode: 19, Reward: -5700.0
Episode: 20, Reward: -7700.0
Episode: 21, Reward: -5800.0
Episode: 22, Reward: -5300.0
Episode: 23, Reward: -3900.0
Episode: 24, Reward: -3100.0
Episode: 25, Reward: -8100.0
Episode: 26, Reward: -3600.0
Episode: 27, Reward: -2100.0
Episode: 28, Reward: -3000.0
Episode: 29, Reward: -1300.0
Episode: 30, Reward: -1400.0
Episode: 31, Reward: -1800.0
Episode: 32, Reward: -4800.0
Episode: 33, Reward: -7700.0
Episode: 

Loading Q-Learning trained Q-Table and checking if successful

In [83]:
trained_q = load('Q_Table - Q-Learning.pkl')
print(trained_q)

[[-99.36373      0.70696515 -99.36373      0.70696515]
 [-99.29304      0.78551686   0.6362686    0.78551686]
 [-99.214485     0.8727965    0.70696515   0.8727965 ]
 ...
 [ 72.9        -19.          72.9         90.        ]
 [ 81.         -10.          81.         100.        ]
 [  0.           0.           0.           0.        ]]


---

# SARSA

---

In [84]:
def sarsa(env, alpha=1, gamma=0.9,  epsilon=1, epsilon_decay=0.005):

    Q = np.zeros((env.grid_size[0]*env.grid_size[1], len(env.action_space)), dtype=np.float32) #Initialize the Q table to all 0s

    for e in range(1000): #Run 1k training runs

        state = env.reset() #Part of OpenAI where you need to reset at the start of each run
        total_reward = 0 #Set initial reward to 0

        while True: #Loop until done == True
            #IF random number is less than epsilon grab the random action else grab the argument max of Q[state]

            current_state_index = env.current_pos[0] + env.current_pos[1]*env.observation_space[0] # Obtain the index of the state

            action = compute_action(current_state_index, Q, epsilon, env) # Compute the action for the current state using Q-Table

            posp1, reward, done = env.step(action) # Send the action to the environment and obtain the new position, the reward and the termination flag

            state_tp1_index = posp1[0] + posp1[1]*env.observation_space[0] # Compute the index of the state at t+1
            action_tp1 = compute_action(state_tp1_index, Q, epsilon, env) # Compute the action for the next state using Q-Table

            total_reward += reward # Increment the reward

            Q[current_state_index][action] = Q[current_state_index][action] + alpha * (reward + gamma*Q[state_tp1_index][action_tp1] - Q[current_state_index][action])

             #Make sure to keep random at 10%

            if done:
                print(f"Episode: {e}, Reward: {total_reward}")
                break

        epsilon *= np.exp(-epsilon_decay)

    return Q

Effective running of SARSA and saving of the trained Q-Table

In [85]:
s = sarsa(environment)
save('Q_Table - SARSA.pkl', s)

Episode: 0, Reward: -21400.0
Episode: 1, Reward: -64300.0
Episode: 2, Reward: -12700.0
Episode: 3, Reward: -55700.0
Episode: 4, Reward: -42300.0
Episode: 5, Reward: -75600.0
Episode: 6, Reward: -1400.0
Episode: 7, Reward: -47300.0
Episode: 8, Reward: -42200.0
Episode: 9, Reward: -9500.0
Episode: 10, Reward: -13600.0
Episode: 11, Reward: -38000.0
Episode: 12, Reward: -20200.0
Episode: 13, Reward: -114500.0
Episode: 14, Reward: -32900.0
Episode: 15, Reward: -111400.0
Episode: 16, Reward: -21700.0
Episode: 17, Reward: -156100.0
Episode: 18, Reward: -14000.0
Episode: 19, Reward: -11700.0
Episode: 20, Reward: -45900.0
Episode: 21, Reward: -45200.0
Episode: 22, Reward: -28500.0
Episode: 23, Reward: -8100.0
Episode: 24, Reward: -69200.0
Episode: 25, Reward: -42300.0
Episode: 26, Reward: -19200.0
Episode: 27, Reward: -27000.0
Episode: 28, Reward: -29500.0
Episode: 29, Reward: -33600.0
Episode: 30, Reward: -47600.0
Episode: 31, Reward: -1800.0
Episode: 32, Reward: -8600.0
Episode: 33, Reward: -

Loading SARSA trained Q-Table and checking if successful

In [86]:
trained_s = load('Q_Table - SARSA.pkl')
print(trained_s)

[[-100.         0.      -143.04672  -90.     ]
 [-100.       -81.       -72.9        0.     ]
 [-100.         0.       -59.049    -90.     ]
 ...
 [  72.9      -77.12321  -78.21871  -24.39   ]
 [  53.1441   -10.        65.61     100.     ]
 [   0.         0.         0.         0.     ]]


---

# Alternating Q-Learning / SARSA

---

In [90]:
def alternating(env, alpha=1, gamma=0.9,  epsilon=1, epsilon_decay=0.005):

    Q = np.zeros((env.grid_size[0]*env.grid_size[1], len(env.action_space)), dtype=np.float32) #Initialize the Q table to all 0s

    for e in range(1000): #Run 1k training runs

        state = env.reset() #Part of OpenAI where you need to reset at the start of each run
        total_reward = 0 #Set initial reward to 0

        while True: #Loop until done == True

            random_num = random.random() # Generate a random number between 0 and 1

            current_state_index = env.current_pos[0] + env.current_pos[1]*env.observation_space[0] # Obtain the index of the state

            action = compute_action(current_state_index, Q, epsilon, env) # Compute the action for the current state using Q-Table

            posp1, reward, done = env.step(action) # Send the action to the environment and obtain the new position, the reward and the termination flag

            state_tp1_index = posp1[0] + posp1[1]*env.observation_space[0] # Compute the index of the state at t+1
            action_tp1 = compute_action(state_tp1_index, Q, epsilon, env) # Compute the action for the next state using Q-Table

            total_reward += reward # Increment the reward

            if (random_num <= 0.5): # We use Q-learning
                Q[current_state_index][action] = Q[current_state_index][action] + alpha * (reward + gamma * np.max(Q[state_tp1_index]) - Q[current_state_index][action])

            else: # We use SARSA
                Q[current_state_index][action] = Q[current_state_index][action] + alpha * (reward + gamma*Q[state_tp1_index][action_tp1] - Q[current_state_index][action])

            if done:
                print(f"Episode: {e}, Reward: {total_reward}")
                break

        epsilon *= np.exp(-epsilon_decay)

    return Q

Effective running of alternating Q-Learning/SARSA and saving of the trained Q-Table

In [92]:
a = alternating(environment)
save('Q_Table - Alternating.pkl', a)

Episode: 0, Reward: -25000.0
Episode: 1, Reward: -190600.0
Episode: 2, Reward: -9700.0
Episode: 3, Reward: -44500.0
Episode: 4, Reward: -23500.0
Episode: 5, Reward: -26500.0
Episode: 6, Reward: -103100.0
Episode: 7, Reward: -64000.0
Episode: 8, Reward: -224200.0
Episode: 9, Reward: -41500.0
Episode: 10, Reward: -4700.0
Episode: 11, Reward: -67500.0
Episode: 12, Reward: -9100.0
Episode: 13, Reward: -4500.0
Episode: 14, Reward: -8100.0
Episode: 15, Reward: -9400.0
Episode: 16, Reward: -3700.0
Episode: 17, Reward: -3600.0
Episode: 18, Reward: -5700.0
Episode: 19, Reward: -4200.0
Episode: 20, Reward: -19200.0
Episode: 21, Reward: -3600.0
Episode: 22, Reward: -4200.0
Episode: 23, Reward: -2300.0
Episode: 24, Reward: -7500.0
Episode: 25, Reward: -8300.0
Episode: 26, Reward: -3000.0
Episode: 27, Reward: -6300.0
Episode: 28, Reward: -3300.0
Episode: 29, Reward: -4700.0
Episode: 30, Reward: -1200.0
Episode: 31, Reward: -4000.0
Episode: 32, Reward: -4100.0
Episode: 33, Reward: -2500.0
Episode: 3

Loading alternating trained Q-Table and checking if successful

In [94]:
trained_a = load('Q_Table - Alternating.pkl')
print(trained_a)

[[-9.9363731e+01  7.0696515e-01 -9.9363731e+01 -8.9582550e+01]
 [-9.9536163e+01  7.7355430e-02 -8.9868996e+01  7.7355430e-02]
 [-9.9922646e+01  8.5950479e-02  8.5950479e-02  8.5950479e-02]
 ...
 [ 3.8742046e+01 -1.9000000e+01  7.2900002e+01  9.0000000e+01]
 [ 8.1000000e+01 -1.0000000e+01  8.1000000e+01  1.0000000e+02]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]]


---

# Deep Q-Learning

---

---

# Spatial Computing for Path Planning - SCPP - Personalized algorithm

---